export const ClientsData={

    items:[
        {
            id:0,
            name:"JO",
            age:23,
            image:"images/usersimg/user0.jpg"
        },
        {
            id:1,
            name:"Eylon",
            age:26,
            image:"images/usersimg/user1.jpg"
        },
        {
            id:2,
            name:"Daria",
            age:32,
            image:"images/usersimg/user2.jpg"
        },
        {
            id:3,
            name:"Coman",
            age:27,
            image:"images/usersimg/user3.jpg"
        },
        {
            id:4,
            name:"Demble",
            age:28,
            image:"images/usersimg/user4.jpg"
        },
        {
            id:5,
            name:"Matis",
            age:37,
            image:"images/usersimg/user5.jpg"
        },
        {
            id:6,
            name:"Broli",
            age:18,
            image:"images/usersimg/user6.jpg"
        },
        {
            id:7,
            name:"Jorden",
            age:24,
            image:"images/usersimg/user7.jpg"
        },
        {
            id:8,
            name:"Kyle",
            age:31,
            image:"images/usersimg/user8.jpg"
        },
        {
            id:9,
            name:"Koman",
            age:24,
            image:"images/usersimg/user9.jpg"
        },
        {
            id:10,
            name:"Bornu",
            age:42,
            image:"images/usersimg/user10.jpg"
        },
        {
            id:11,
            name:"Romani",
            age:35,
            image:"images/usersimg/user11.jpg"
        },
    

    ]
}